spring.application.name=carrinho-service
server.port=8080
services.estoque.url=http://estoque-service:8080/estoque

jwt.secret=${JWT_SECRET:demo-local-secret-must-have-at-least-32-bytes}

spring.artemis.mode=native
spring.artemis.broker-url=${ARTEMIS_BROKER_URL:tcp://artemis-broker:61616}
spring.artemis.user=${ARTEMIS_USER:artemis}
spring.artemis.password=${ARTEMIS_PASSWORD:artemis}
